### ISSUE TITLE
Comments and Questions from Lotus 

### ISSUE THREAD

**Issue by toastliu** [wyliadrian/BIS-687#3]
The research plan is well-structured, and the research questions are clear.  It is a promising approach to use the random forest model to identify the most significant predictors of sleep quality-related variables, as it allows for the examination of complex relationships simultaneously. Good job! 

The team addressed my first question: "How will missing data be handled in the analysis of this study, and what potential impact could missing data have on the results" very well in class. Thank you for the explanation. Besides this question, I am very interested in the following questions as well: 

- Have you considered utilizing other models besides random forest? I think it will be beneficial to train another predictive model and then make comparisons of their performance.
- Are there any other factors that may influence the relationship between sleep conditions and physical activity levels, such as age, gender, or body mass index? Will these factors be taken into account in the analysis?

Thanks in advance. Good job!

**Comment by ccfeng0716** [comment]
Thanks for your suggestions! 

So for the first question, we choose the random forest model because it works well with both categorical and numerical data, and it can handle both linear and non-linear relationships. We will have further discussions and train other models if time permits. For the second question, yes the physical activity level and other features such as age, gender, and BMI will be included in our model. We want to compare the models with and without physical activity to see if this feature makes a significant effect on sleep conditions combined with other features.

Please let me know if you have further questions. Thanks again for your advice!
